<?php
/**
 * Register ACF local field groups programmatically.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( function_exists( 'acf_add_local_field_group' ) ) {

	// Home Page settings with tabs
	acf_add_local_field_group( array(
		'key' => 'group_home_fields',
		'title' => 'Home Page Settings',
		'fields' => array(
			// TAB: Banner Slider
			array(
				'key' => 'field_tab_banner',
				'label' => 'Banner Slider',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_banner_slides',
				'label' => 'Banner Slides',
				'name' => 'banner_slides',
				'type' => 'repeater',
				'instructions' => 'Add the slides to display in the home page banner slider.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_slide_title',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Slide',
				'sub_fields' => array(
					array(
						'key' => 'field_slide_image',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Upload or select the background image for this slide.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array(
						'key' => 'field_slide_label',
						'label' => 'Category Label',
						'name' => 'label',
						'type' => 'text',
						'instructions' => 'E.g., General Construction, Septic Systems',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_slide_title',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => 'The main heading text for the slide.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_slide_description',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => 'A short paragraph description.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
					),
					array(
						'key' => 'field_slide_button',
						'label' => 'Button Link/Action',
						'name' => 'button',
						'type' => 'link',
						'instructions' => 'URL and text for the slide action button (e.g., Book Now).',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),

			// TAB: Services Section
			array(
				'key' => 'field_tab_services',
				'label' => 'Services Section',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_services_section_subtitle',
				'label' => 'Services Subtitle',
				'name' => 'services_section_subtitle',
				'type' => 'text',
				'instructions' => 'E.g., Our Services',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Our Services',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_services_section_title',
				'label' => 'Services Title',
				'name' => 'services_section_title',
				'type' => 'text',
				'instructions' => 'Title of the section. You can use HTML tags like &lt;span class="highlight"&gt;&lt;/span&gt;.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Construction <span class="highlight">Services</span> We Provide',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_services_section_description',
				'label' => 'Services Description',
				'name' => 'services_section_description',
				'type' => 'textarea',
				'instructions' => 'Brief description of the services section.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Jacob General Construction offers a range of services to meet your construction needs, from grading and site preparation to septic system installation and concrete work.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
			// TAB: Testimonials Section
			array(
				'key' => 'field_tab_testimonials',
				'label' => 'Testimonials Section',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_testimonials_section_subtitle',
				'label' => 'Testimonials Subtitle',
				'name' => 'testimonials_section_subtitle',
				'type' => 'text',
				'instructions' => 'E.g., Testimonials',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Testimonials',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_testimonials_section_title',
				'label' => 'Testimonials Title',
				'name' => 'testimonials_section_title',
				'type' => 'text',
				'instructions' => 'Title of the section. You can use HTML tags.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'What Our <span class="highlight">Clients</span> Say',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_testimonials_section_description',
				'label' => 'Testimonials Description',
				'name' => 'testimonials_section_description',
				'type' => 'textarea',
				'instructions' => 'Brief description of the testimonials section.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'We take pride in delivering quality construction services that exceed expectations. Here\'s what our clients have to say about working with Jacob General Construction.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
			// TAB: FAQ Section
			array(
				'key' => 'field_tab_faq',
				'label' => 'FAQ Section',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_faq_section_subtitle',
				'label' => 'FAQ Subtitle',
				'name' => 'faq_section_subtitle',
				'type' => 'text',
				'instructions' => 'E.g., FAQ',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'FAQ',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_faq_section_title',
				'label' => 'FAQ Title',
				'name' => 'faq_section_title',
				'type' => 'text',
				'instructions' => 'Title of the section. You can use HTML tags.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Frequently Asked <span class="highlight">Questions</span>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_faq_section_description',
				'label' => 'FAQ Description',
				'name' => 'faq_section_description',
				'type' => 'textarea',
				'instructions' => 'Brief description of the FAQ section.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Have questions about site grading, septic permits, or concrete placement? Here are answers to our most common client inquiries.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_faq_items',
				'label' => 'FAQ Items',
				'name' => 'faq_items',
				'type' => 'repeater',
				'instructions' => 'Add individual FAQ items (questions and answers).',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_faq_question',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add FAQ',
				'sub_fields' => array(
					array(
						'key' => 'field_faq_question',
						'label' => 'Question',
						'name' => 'question',
						'type' => 'text',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_faq_answer',
						'label' => 'Answer',
						'name' => 'answer',
						'type' => 'textarea',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 4,
						'new_lines' => 'wpautop',
					),
				),
			),
			// TAB: Gallery Section
			array(
				'key' => 'field_tab_gallery',
				'label' => 'Gallery Section',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_gallery_section_subtitle',
				'label' => 'Gallery Subtitle',
				'name' => 'gallery_section_subtitle',
				'type' => 'text',
				'instructions' => 'E.g., Project Gallery',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Project Gallery',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_gallery_section_title',
				'label' => 'Gallery Title',
				'name' => 'gallery_section_title',
				'type' => 'text',
				'instructions' => 'Title of the section. You can use HTML tags.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Recent Site Projects We\'ve <span class="highlight">Completed</span>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_gallery_section_description',
				'label' => 'Gallery Description',
				'name' => 'gallery_section_description',
				'type' => 'textarea',
				'instructions' => 'Brief description of the gallery section.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Take a look at the quality and cleanliness of our site preparations, septic designs, and concrete finishes.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
			// TAB: Blog Section
			array(
				'key' => 'field_tab_blog',
				'label' => 'Blog Section',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_blog_section_subtitle',
				'label' => 'Blog Subtitle',
				'name' => 'blog_section_subtitle',
				'type' => 'text',
				'instructions' => 'E.g., Latest News',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Latest News',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_blog_section_title',
				'label' => 'Blog Title',
				'name' => 'blog_section_title',
				'type' => 'text',
				'instructions' => 'Title of the section. You can use HTML tags.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Articles & Construction <span class="highlight">Tips</span>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_blog_section_description',
				'label' => 'Blog Description',
				'name' => 'blog_section_description',
				'type' => 'textarea',
				'instructions' => 'Brief description of the blog section.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Helpful advice on septic maintenance, land grading, and concrete laying to keep your foundations strong.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),

			// TAB: Quote Sidebar Section
			array(
				'key' => 'field_tab_quote_sidebar',
				'label' => 'Quote Sidebar',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_quote_sidebar_title',
				'label' => 'Sidebar Title',
				'name' => 'quote_sidebar_title',
				'type' => 'text',
				'instructions' => 'E.g., Why Work With Us?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Why Work With Us?',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_quote_sidebar_hours',
				'label' => 'Office Hours',
				'name' => 'quote_sidebar_hours',
				'type' => 'text',
				'instructions' => 'E.g., Mon - Fri: 7:00 AM - 5:00 PM',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Mon - Fri: 7:00 AM - 5:00 PM',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_quote_sidebar_checklist',
				'label' => 'Why Work With Us Checklist',
				'name' => 'quote_sidebar_checklist',
				'type' => 'repeater',
				'instructions' => 'Add the checklist points displayed in the sidebar.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_chk_title',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Checkpoint',
				'sub_fields' => array(
					array(
						'key' => 'field_chk_icon',
						'label' => 'Icon Class',
						'name' => 'icon',
						'type' => 'text',
						'instructions' => 'Enter the FontAwesome class (e.g. fa-solid fa-shield-halved).',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'fa-solid fa-shield-halved',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_chk_title',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => 'Point title.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '70',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_chk_desc',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => 'Point description detail.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/Home.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	) );

	// Service CPT fields
	acf_add_local_field_group( array(
		'key' => 'group_service_details',
		'title' => 'Service Details',
		'fields' => array(
			// TAB: Service Icon
			array(
				'key' => 'field_service_tab_icon',
				'label' => 'Icon Settings',
				'type' => 'tab',
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_service_icon',
				'label' => 'Service Icon Class',
				'name' => 'service_icon',
				'type' => 'text',
				'instructions' => 'Enter the FontAwesome icon class (e.g. fa-solid fa-tractor).',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'fa-solid fa-tractor',
				'placeholder' => 'fa-solid fa-tractor',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),

			// TAB: Watch Us In Action (Video)
			array(
				'key' => 'field_service_tab_video',
				'label' => 'Watch Us In Action',
				'type' => 'tab',
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_service_video_url',
				'label' => 'Video Embed URL',
				'name' => 'service_video_url',
				'type' => 'url',
				'instructions' => 'Enter the YouTube Embed URL (e.g. https://www.youtube.com/embed/dQw4w9WgXcQ).',
				'required' => 0,
				'wrapper' => array(
					'width' => '100',
				),
			),
			array(
				'key' => 'field_service_video_cover',
				'label' => 'Video Cover Image',
				'name' => 'service_video_cover',
				'type' => 'image',
				'instructions' => 'Upload a custom cover image to display before playing the video.',
				'required' => 0,
				'return_format' => 'array',
				'preview_size' => 'medium',
				'wrapper' => array(
					'width' => '50',
				),
			),
			array(
				'key' => 'field_service_video_caption',
				'label' => 'Video Caption Text',
				'name' => 'service_video_caption',
				'type' => 'text',
				'instructions' => 'Caption displayed below the video widget.',
				'required' => 0,
				'wrapper' => array(
					'width' => '50',
				),
			),

			// TAB: Jobsite Photos
			array(
				'key' => 'field_service_tab_photos',
				'label' => 'Jobsite Photos',
				'type' => 'tab',
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_service_jobsite_photos',
				'label' => 'Jobsite Photos',
				'name' => 'service_jobsite_photos',
				'type' => 'gallery',
				'instructions' => 'Select or upload photos taken at actual jobsites for this service.',
				'required' => 0,
				'return_format' => 'array',
				'preview_size' => 'medium',
			),

			// TAB: Our Process
			array(
				'key' => 'field_service_tab_process',
				'label' => 'Our Process',
				'type' => 'tab',
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_service_process_subtitle',
				'label' => 'Process Subtitle',
				'name' => 'service_process_subtitle',
				'type' => 'text',
				'instructions' => 'Sub-heading below the "Our Process" title.',
				'required' => 0,
				'default_value' => 'Steps we take to ensure your project is completed right.',
				'wrapper' => array(
					'width' => '100',
				),
			),
			array(
				'key' => 'field_service_process_steps',
				'label' => 'Process Steps',
				'name' => 'service_process_steps',
				'type' => 'repeater',
				'instructions' => 'Define the step-by-step process stages.',
				'required' => 0,
				'layout' => 'row',
				'button_label' => 'Add Step',
				'sub_fields' => array(
					array(
						'key' => 'field_service_step_title',
						'label' => 'Step Title',
						'name' => 'title',
						'type' => 'text',
						'required' => 1,
						'wrapper' => array(
							'width' => '30',
						),
					),
					array(
						'key' => 'field_service_step_desc',
						'label' => 'Step Description',
						'name' => 'description',
						'type' => 'textarea',
						'required' => 1,
						'rows' => 3,
						'wrapper' => array(
							'width' => '70',
						),
					),
				),
			),

			// TAB: FAQ Section
			array(
				'key' => 'field_service_tab_faq',
				'label' => 'FAQ Section',
				'type' => 'tab',
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_service_faq_subtitle',
				'label' => 'FAQ Subtitle',
				'name' => 'faq_section_subtitle',
				'type' => 'text',
				'wrapper' => array( 'width' => '33' ),
			),
			array(
				'key' => 'field_service_faq_title',
				'label' => 'FAQ Title',
				'name' => 'faq_section_title',
				'type' => 'text',
				'wrapper' => array( 'width' => '33' ),
			),
			array(
				'key' => 'field_service_faq_desc',
				'label' => 'FAQ Description',
				'name' => 'faq_section_description',
				'type' => 'textarea',
				'rows' => 3,
				'wrapper' => array( 'width' => '33' ),
			),
			array(
				'key' => 'field_service_faq_items',
				'label' => 'FAQ Items',
				'name' => 'faq_items',
				'type' => 'repeater',
				'layout' => 'row',
				'button_label' => 'Add FAQ',
				'sub_fields' => array(
					array(
						'key' => 'field_service_faq_q',
						'label' => 'Question',
						'name' => 'question',
						'type' => 'text',
						'required' => 1,
					),
					array(
						'key' => 'field_service_faq_a',
						'label' => 'Answer',
						'name' => 'answer',
						'type' => 'wysiwyg',
						'required' => 1,
					),
				),
			),

			// TAB: Testimonials Section
			array(
				'key' => 'field_service_tab_testimonials',
				'label' => 'Testimonials Section',
				'type' => 'tab',
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_service_testimonials_subtitle',
				'label' => 'Testimonials Subtitle',
				'name' => 'testimonials_section_subtitle',
				'type' => 'text',
				'wrapper' => array( 'width' => '33' ),
			),
			array(
				'key' => 'field_service_testimonials_title',
				'label' => 'Testimonials Title',
				'name' => 'testimonials_section_title',
				'type' => 'text',
				'wrapper' => array( 'width' => '33' ),
			),
			array(
				'key' => 'field_service_testimonials_desc',
				'label' => 'Testimonials Description',
				'name' => 'testimonials_section_description',
				'type' => 'textarea',
				'rows' => 3,
				'wrapper' => array( 'width' => '33' ),
			),

			// TAB: Projects Section
			array(
				'key' => 'field_service_tab_projects',
				'label' => 'Gallery / Projects Section',
				'type' => 'tab',
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_service_projects_subtitle',
				'label' => 'Gallery Subtitle',
				'name' => 'gallery_section_subtitle',
				'type' => 'text',
				'wrapper' => array( 'width' => '33' ),
			),
			array(
				'key' => 'field_service_projects_title',
				'label' => 'Gallery Title',
				'name' => 'gallery_section_title',
				'type' => 'text',
				'wrapper' => array( 'width' => '33' ),
			),
			array(
				'key' => 'field_service_projects_desc',
				'label' => 'Gallery Description',
				'name' => 'gallery_section_description',
				'type' => 'textarea',
				'rows' => 3,
				'wrapper' => array( 'width' => '33' ),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'service',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	) );

	// Testimonial CPT fields
	acf_add_local_field_group( array(
		'key' => 'group_testimonial_details',
		'title' => 'Testimonial Details',
		'fields' => array(
			array(
				'key' => 'field_client_role',
				'label' => 'Client Designation/Role',
				'name' => 'client_role',
				'type' => 'text',
				'instructions' => 'E.g., Homeowner, Property Owner, Contractor',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Homeowner',
				'placeholder' => 'Homeowner',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_testimonial_rating',
				'label' => 'Rating (Stars)',
				'name' => 'testimonial_rating',
				'type' => 'select',
				'instructions' => 'Select client rating (1 to 5 stars).',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					5 => '5 Stars',
					4 => '4 Stars',
					3 => '3 Stars',
					2 => '2 Stars',
					1 => '1 Star',
				),
				'default_value' => 5,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'testimonial',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	) );

	// About Page fields
	acf_add_local_field_group( array(
		'key' => 'group_about_page',
		'title' => 'About Page Content',
		'fields' => array(
			// TAB: Story Section
			array(
				'key' => 'field_about_tab_story',
				'label' => 'Our Story',
				'type' => 'tab',
			),
			array(
				'key' => 'field_about_story_subheading',
				'label' => 'Story Subheading',
				'name' => 'about_story_subheading',
				'type' => 'text',
				'default_value' => 'Our Story',
			),
			array(
				'key' => 'field_about_story_heading',
				'label' => 'Story Heading',
				'name' => 'about_story_heading',
				'type' => 'text',
				'default_value' => 'Georgia Roots & Reliable <span class="highlight">Site Work</span>',
			),
			array(
				'key' => 'field_about_story_content',
				'label' => 'Story Content',
				'name' => 'about_story_content',
				'type' => 'wysiwyg',
				'default_value' => '<p class="lead_text">Jacob General Construction has been serving the Metro Atlanta area, delivering precise excavation, land clearing, grading, septic installations, and heavy concrete paving services.</p><p>We built our company on the values of absolute clarity, transparent pricing, and quality craftsmanship. We know that every residential structure, commercial parking pad, or septic drain field starts with meticulous ground preparation. That\'s why our crew treats every job site with an engineering eye for detail, checking grades, soil dynamics, and runoffs to prevent future foundation failures.</p><p>Whether you need clay soil graded for a new build, a GDOT-grade driveway concrete pour, or a local county health permit inspection for septic design, we bring the right operators, state-of-the-art equipment, and local expertise to get the job done right.</p>',
			),
			array(
				'key' => 'field_about_story_image',
				'label' => 'Story Image',
				'name' => 'about_story_image',
				'type' => 'image',
				'return_format' => 'url',
			),

			// TAB: Core Values Section
			array(
				'key' => 'field_about_tab_values',
				'label' => 'Core Values',
				'type' => 'tab',
			),
			array(
				'key' => 'field_about_values_subheading',
				'label' => 'Values Subheading',
				'name' => 'about_values_subheading',
				'type' => 'text',
				'default_value' => 'Our Core Values',
			),
			array(
				'key' => 'field_about_values_heading',
				'label' => 'Values Heading',
				'name' => 'about_values_heading',
				'type' => 'text',
				'default_value' => 'What Guides Our <span class="highlight">Workmanship</span>',
			),
			array(
				'key' => 'field_about_values_description',
				'label' => 'Values Description',
				'name' => 'about_values_description',
				'type' => 'textarea',
				'default_value' => 'We strive to bring top-tier service, structural engineering guidelines, and dependable schedules to Georgia clients.',
			),
			array(
				'key' => 'field_about_values_list',
				'label' => 'Core Values Checklist',
				'name' => 'about_values_list',
				'type' => 'repeater',
				'layout' => 'block',
				'button_label' => 'Add Value',
				'sub_fields' => array(
					array(
						'key' => 'field_about_val_icon',
						'label' => 'Icon Class',
						'name' => 'icon',
						'type' => 'text',
						'default_value' => 'fa-solid fa-award',
					),
					array(
						'key' => 'field_about_val_title',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
					),
					array(
						'key' => 'field_about_val_desc',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/about.php',
				),
			),
		),
	) );

	// CTA Section fields (Shared)
	acf_add_local_field_group( array(
		'key' => 'group_cta_section',
		'title' => 'Call To Action (CTA)',
		'fields' => array(
			array(
				'key' => 'field_cta_subtitle',
				'label' => 'CTA Subtitle',
				'name' => 'cta_subtitle',
				'type' => 'text',
				'instructions' => 'E.g., Have a Construction Project in Mind?',
				'required' => 0,
				'wrapper' => array(
					'width' => '50',
				),
				'default_value' => 'Have a Construction Project in Mind?',
			),
			array(
				'key' => 'field_cta_title',
				'label' => 'CTA Title',
				'name' => 'cta_title',
				'type' => 'text',
				'instructions' => 'E.g., Let\'s Get Your Project Moving Today',
				'required' => 0,
				'wrapper' => array(
					'width' => '50',
				),
				'default_value' => 'Let\'s Get Your Project Moving Today',
			),
			array(
				'key' => 'field_cta_description',
				'label' => 'CTA Description',
				'name' => 'cta_description',
				'type' => 'textarea',
				'instructions' => 'Brief description of the call to action.',
				'required' => 0,
				'wrapper' => array(
					'width' => '100',
				),
				'default_value' => 'From site grading to concrete pouring and septic setups, our crew delivers clean work that lasts. Contact us now to schedule an inspection.',
				'rows' => 3,
			),
			array(
				'key' => 'field_cta_primary_button',
				'label' => 'Primary Button (Call)',
				'name' => 'cta_primary_button',
				'type' => 'link',
				'instructions' => 'E.g. Link to Phone or Booking.',
				'required' => 0,
				'wrapper' => array(
					'width' => '50',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_cta_secondary_button',
				'label' => 'Secondary Button (Quote)',
				'name' => 'cta_secondary_button',
				'type' => 'link',
				'instructions' => 'E.g. Link to Quote section (#quote-name).',
				'required' => 0,
				'wrapper' => array(
					'width' => '50',
				),
				'return_format' => 'array',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/Home.php',
				),
			),
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/services.php',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'CTA section shown at the bottom of pages.',
	) );

}
